name: Handle issues

on:
  issues:
    types: [opened]  # trigger only when an issue is opened

jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue event details
        run: echo "${{ toJson(github.event) }}"

      # Uncomment below to create a new issue automatically when an issue is opened
      # - name: Create a follow-up issue
      #   uses: peter-evans/create-issue@v4
      #   with:
      #     title: "Follow-up: Issue #${{ github.event.issue.number }} opened"
      #     body: |
      #       A new issue was just opened by @${{ github.event.issue.user.login }}.
      #       Please review and take action.
